#ifndef __JMT_IOCTL_H__
#define __JMT_IOCTL_H__
#define JMT_BASE_IO_OFFSET          0
#define JMT101_IOCTL_MAGIC_NO       0xFC
#define JMT_IOCTL_BASE(x)           JMT_BASE_IO_OFFSET+x
#define JMT_IOCTL_START_CAPTURE     _IO(JMT101_IOCTL_MAGIC_NO, JMT_IOCTL_BASE(0))
#define JMT_IOCTL_ABORT_CAPTURE     _IO(JMT101_IOCTL_MAGIC_NO, JMT_IOCTL_BASE(1))
#define JMT_IOCTL_READ_REGISTER     _IOWR(JMT101_IOCTL_MAGIC_NO, JMT_IOCTL_BASE(2), unsigned int)
#define JMT_IOCTL_WRITE_REGISTER    _IOW(JMT101_IOCTL_MAGIC_NO, JMT_IOCTL_BASE(3), unsigned int)
#define JMT_IOCTL_SOFT_RESET        _IOW(JMT101_IOCTL_MAGIC_NO, JMT_IOCTL_BASE(5), unsigned int)
#define JMT_IOCTL_INIT_REG          _IOW(JMT101_IOCTL_MAGIC_NO, JMT_IOCTL_BASE(6), unsigned int)
#define JMT_IOCTL_READ_ATTR         _IOWR(JMT101_IOCTL_MAGIC_NO, JMT_IOCTL_BASE(9), unsigned int) 
#define JMT_IOCTL_RV          _IOWR(JMT101_IOCTL_MAGIC_NO, JMT_IOCTL_BASE(10), unsigned int)
#define JMT_IOCTL_SET_REG           _IOWR(JMT101_IOCTL_MAGIC_NO, JMT_IOCTL_BASE(11), unsigned int)
#define JMT_IOCTL_SET_OP           _IOWR(JMT101_IOCTL_MAGIC_NO, JMT_IOCTL_BASE(12), unsigned int)
#define JMT_IOCTL_SET_CLOCK_SPEED           _IOWR(JMT101_IOCTL_MAGIC_NO, JMT_IOCTL_BASE(13), unsigned int)

#define JMT_IOCTL_WRITE_ATTR         _IOWR(JMT101_IOCTL_MAGIC_NO, JMT_IOCTL_BASE(14), unsigned int) 
#define JMT_IOCTL_SET_VR            _IOWR(JMT101_IOCTL_MAGIC_NO, JMT_IOCTL_BASE(15), unsigned int) 
#define JMT_IOCTL_READ_RAW            _IOWR(JMT101_IOCTL_MAGIC_NO, JMT_IOCTL_BASE(16), unsigned int) 

#endif


